# Generated by Django 4.0.5 on 2022-06-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_rename_products_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Categories",
        ),
    ]
