# Generated by Django 4.0.5 on 2022-06-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
